---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: {{ template "www-littleman-co.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "www-littleman-co.fullname" . }}
spec:
  hosts:
    - "littleman.co"
    - "www.littleman.co"
  gateways:
   - {{ template "www-littleman-co.fullname" . }}
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-www-littleman-co
