baseURL: https://www.littleman.co
languageCode: en-us
title: littleman.co
theme: littleman-co
googleAnalytics:
publishDir: "web"

pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
# See https://xyproto.github.io/splash/docs/all.html for more styles
pygmentsStyle: pygments

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    url: /
    weight: 1
  - name: Blog
    url: /blog/
    weight: 2
  - name: Docs
    url: /docs/
    weight: 3
  - name: Get Started
    url: /get-started/
    weight: 4

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: Simple, Beautiful web development.
  footerText: ⓒ Andrew Howden, 2019
  hideFooter: false
